/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo51.views;

import java.awt.Color;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultCellEditor;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;
import universidadgrupo51.accesoAdatos.AlumnoData;
import universidadgrupo51.accesoAdatos.InscripcionData;
import universidadgrupo51.entidades.Alumno;
import universidadgrupo51.entidades.Inscripcion;
import universidadgrupo51.entidades.Materia;

/**
 *
 * @author Nico
 */
public class MenuNotas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable(int f, int c) {
            
            if (c == 0 || c == 1) {
                return false;
            } else {
                return true;
            }
            
        }
    };

    private InscripcionData inscriData = new InscripcionData();
    private AlumnoData alumData = new AlumnoData();

    /**
     * Creates new form MenuNotas
     */
    public MenuNotas() {
        initComponents();
        llenarCabecera();
        llenarCombo();
        modelo.setRowCount(0);
        getContentPane().setBackground(new Color(112, 194, 174));
        
        tablaNotas.setRowHeight(25); // Establece la altura en píxeles según tus necesidades
        
        /*
        NUEVO CAMBIO 19/9
        */
        // Asignar el editor de celdas personalizado a la columna de notas
        tablaNotas.getColumnModel().getColumn(2).setCellEditor(new EditorCelda());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxAlumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestión de Notas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carga de Notas");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione un Alumno: ");

        comboBoxAlumno.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        comboBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlumnoActionPerformed(evt);
            }
        });

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        guardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(comboBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardar)
                        .addGap(109, 109, 109)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlumnoActionPerformed
        completarTabla();

        //Se completa la accion en el metodo!
        /*
        for (Inscripcion inscripcion : inscriData.obtenerInscripcionesPorAlumno(alumSelec.getIdAlumno())) {
            modelo.addRow(new Object[]{inscripcion.getMateria().getIdMateria(), inscripcion.getMateria().getNombre(), inscripcion.getNota()});
        }
         */
        //Otra posibilidad!
    }//GEN-LAST:event_comboBoxAlumnoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        /*
        int filaSelect = tablaNotas.getSelectedRow();
        String NotaStr = JOptionPane.showInputDialog(this, "Ingrese la nota a modificar");
        */
         /*
        
        NUEVO CAMBIO 21/9
        */
        if (tablaNotas.isEditing()) {
            JOptionPane.showMessageDialog(this, "Finaliza la edición de la celda con ENTER antes de guardar.", "Celda en edición", JOptionPane.WARNING_MESSAGE);
            return; // No continuar con el proceso de guardado
        }
        // Detener la edición de la última celda editada (si la hay)
        if (tablaNotas.getCellEditor() != null) {
            tablaNotas.getCellEditor().stopCellEditing();
        }
        
        int filas = tablaNotas.getRowCount();
        
        for (int fila = 0; fila < filas; fila++) {
            
            try {
                
            if (tablaNotas.getSelectedRow() > -1) {
                
                Alumno alumSelec = (Alumno) comboBoxAlumno.getSelectedItem();
                int idAlum = alumSelec.getIdAlumno();
                int idMat = (Integer) tablaNotas.getValueAt(fila, 0);
                String NotaStr = tablaNotas.getValueAt(fila, 2).toString();
                double Nota = Double.parseDouble(NotaStr);

                if (Nota >= 0 && Nota <= 10) {
                    inscriData.actualizarNota(idAlum, idMat, Nota);
                } else {
                    JOptionPane.showMessageDialog(this, "Debe escribir un numero comprendido entre 0 y 10");
                }

            } else {
                JOptionPane.showMessageDialog(this, "No hay fila seleccionada o no hay materias");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Este campo solo permite valores decimales...");
        }
            
        }
        JOptionPane.showMessageDialog(this, "Notas Guardadas");
        completarTabla();
    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> comboBoxAlumno;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables

    private void llenarCabecera() {

        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Nota");
        tablaNotas.setModel(modelo);
    }

    private void borrarFilas() {

        int f = tablaNotas.getRowCount() - 1;
        for (int fila = f; fila >= 0; fila--) {

            modelo.removeRow(fila);
        }
    }

    private void llenarCombo() {

        for (Alumno lista : alumData.listarAlumnos()) {
            comboBoxAlumno.addItem(lista);
        }
    }

    private double obtenerNotaParaMateria(List<Inscripcion> inscripciones, int idMateria) {
        for (Inscripcion inscripcion : inscripciones) {
            if (inscripcion.getMateria().getIdMateria() == idMateria) {
                return inscripcion.getNota();
            }
        }
        // Si no se encuentra la nota, -1 o 0 se devuelve.
        return 0;
    }

    private void completarTabla() {
        borrarFilas();
        Alumno alumSelec = (Alumno) comboBoxAlumno.getSelectedItem();

        for (Materia mat : inscriData.obtenerMateriasCursadas(alumSelec.getIdAlumno())) {
            double nota = obtenerNotaParaMateria(inscriData.obtenerInscripcionesPorAlumno(alumSelec.getIdAlumno()), mat.getIdMateria());
            modelo.addRow(new Object[]{mat.getIdMateria(), mat.getNombre(), nota});
        }
    }
    
    /*
        NUEVO CAMBIO 19/9
    */
    
    // Crear un editor de Celda
    public class EditorCelda extends DefaultCellEditor {
        private JFormattedTextField textField;

        public EditorCelda() {
            super(new JFormattedTextField());
            textField = (JFormattedTextField) getComponent();

            // Configurar el formato para aceptar valores decimales
            DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
            symbols.setDecimalSeparator('.');
            DecimalFormat format = new DecimalFormat("#.##", symbols);
            format.setParseBigDecimal(true);
            NumberFormatter formatter = new NumberFormatter(format);
            formatter.setValueClass(Double.class);
            formatter.setMinimum(0.0);
            formatter.setMaximum(10.0);
            textField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(formatter));
        }
    }
}
