/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo51.views;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import universidadgrupo51.accesoAdatos.MateriaData;
import universidadgrupo51.entidades.Materia;

/**
 *
 * @author tobal
 */
public class MenuMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuMateria
     */
    public MenuMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigoMateria = new javax.swing.JTextField();
        nombreMateria = new javax.swing.JTextField();
        anioMateria = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nuevoBoton = new javax.swing.JButton();
        guardarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        estadoTrue = new javax.swing.JRadioButton();
        estadoFalse = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Gestor de Materias");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Materia");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Año:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");

        codigoMateria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigoMateria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigoMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nombreMateria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        anioMateria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        anioMateria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nuevoBoton.setText("Nuevo");
        nuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBotonActionPerformed(evt);
            }
        });

        guardarBoton.setText("Guardar");
        guardarBoton.setToolTipText("");
        guardarBoton.setEnabled(false);

        eliminarBoton.setText("Eliminar");
        eliminarBoton.setEnabled(false);
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        estado.add(estadoTrue);
        estadoTrue.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoTrue.setText("Activo");
        estadoTrue.setActionCommand("true");
        estadoTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTrueActionPerformed(evt);
            }
        });

        estado.add(estadoFalse);
        estadoFalse.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        estadoFalse.setText("No Activo");
        estadoFalse.setActionCommand("false");
        estadoFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoFalseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(codigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(nombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estadoTrue)
                                .addGap(20, 20, 20)
                                .addComponent(estadoFalse))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(nuevoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoTrue)
                    .addComponent(estadoFalse))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTrueActionPerformed

    private void estadoFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoFalseActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Boton Exit
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nuevoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBotonActionPerformed
        // Boton Nuevo:
        Materia mat = new Materia();
        if (!"".equals(nombreMateria.getText())){
            mat.setNombre(nombreMateria.getText());
            if (!"".equals(anioMateria.getText())){
                mat.setAnio(Integer.valueOf(anioMateria.getText()));

                if (estado.isSelected(estadoTrue.getModel()) || estado.isSelected(estadoFalse.getModel())){
                    if (estado.isSelected(estadoTrue.getModel())){
                        mat.setEstado(true);
                    }
                    else if (estado.isSelected(estadoFalse.getModel())){
                        mat.setEstado(false);
                    }
                    MateriaData matData = new MateriaData();
                    matData.guardarMateria(mat);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Debe selecionar el estado de la materia.");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Debe ingresar el anio de la materia.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre de la materia.");
        }
    }//GEN-LAST:event_nuevoBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MateriaData matData = new MateriaData();
        Materia mat = new Materia();
        
        mat = matData.buscarMateria(Integer.valueOf(codigoMateria.getText()));
        nombreMateria.setText(mat.getNombre());
        anioMateria.setText(String.valueOf(mat.getAnio()));
        if (mat.isEstado()){
            estadoTrue.setSelected(true);
        }
        else{
            estadoFalse.setSelected(true);
        }
        nuevoBoton.setEnabled(false);
        guardarBoton.setEnabled(true);
        eliminarBoton.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioMateria;
    private javax.swing.JTextField codigoMateria;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.ButtonGroup estado;
    private javax.swing.JRadioButton estadoFalse;
    private javax.swing.JRadioButton estadoTrue;
    private javax.swing.JButton guardarBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreMateria;
    private javax.swing.JButton nuevoBoton;
    // End of variables declaration//GEN-END:variables
}
