/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo51.views;

import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuInscripcion = new javax.swing.JMenuItem();
        menuNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuAlumXMateria = new javax.swing.JMenuItem();
        jmenuSalir = new javax.swing.JMenu();
        menuSalirPrograma = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad ULP - Grupo 51");
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumno");

        menuAlumno.setText("Gestion Alumnos");
        menuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(menuAlumno);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        menuMateria.setText("Gestion Materias");
        menuMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(menuMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administracion");

        menuInscripcion.setText("Gestion De Inscripciones");
        menuInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInscripcionActionPerformed(evt);
            }
        });
        jMenu3.add(menuInscripcion);

        menuNotas.setText("Gestion De Notas");
        menuNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNotasActionPerformed(evt);
            }
        });
        jMenu3.add(menuNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        menuAlumXMateria.setText("Alumnos Por Materia");
        menuAlumXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlumXMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(menuAlumXMateria);

        jMenuBar1.add(jMenu4);

        jmenuSalir.setText("Salir");

        menuSalirPrograma.setText("Salir del Programa");
        menuSalirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirProgramaActionPerformed(evt);
            }
        });
        jmenuSalir.add(menuSalirPrograma);

        jMenuBar1.add(jmenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNotasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MenuNotas mNotas = new MenuNotas();
        mNotas.setVisible(true);
        escritorio.add(mNotas);
        escritorio.moveToFront(mNotas);
    }//GEN-LAST:event_menuNotasActionPerformed

    private void menuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumnoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MenuAlumnos menuAlumnos = new MenuAlumnos();
        menuAlumnos.setVisible(true);
        escritorio.add(menuAlumnos);
        escritorio.moveToFront(menuAlumnos);
    }//GEN-LAST:event_menuAlumnoActionPerformed

    private void menuMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MenuMateria mMateria = new MenuMateria();
        mMateria.setVisible(true);
        escritorio.add(mMateria);
        escritorio.moveToFront(mMateria);
    }//GEN-LAST:event_menuMateriaActionPerformed

    private void menuInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInscripcionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll(); //borrar todo lo que haya en el escritorio
        escritorio.repaint(); //lo vuelva a dibujar
        MenuInscripciones mInscripcion = new MenuInscripciones(); //instanciar un objeto de nuestra vista
        mInscripcion.setVisible(true); //hago visible esa instancia
        escritorio.add(mInscripcion); //agregamos al escritorio la ventana
        escritorio.moveToFront(mInscripcion); //trae
    }//GEN-LAST:event_menuInscripcionActionPerformed

    private void menuAlumXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlumXMateriaActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll(); //borrar todo lo que haya en el escritorio
        escritorio.repaint(); //lo vuelva a dibujar
        MenuAlumnosPorMateria apm = new MenuAlumnosPorMateria(); //instanciar un objeto de nuestra vista
        apm.setVisible(true); //hago visible esa instancia
        escritorio.add(apm); //agregamos al escritorio la ventana
        escritorio.moveToFront(apm); //trae al frente
    }//GEN-LAST:event_menuAlumXMateriaActionPerformed

    private void menuSalirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirProgramaActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?", "Confirmar salida", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuSalirProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmenuSalir;
    private javax.swing.JMenuItem menuAlumXMateria;
    private javax.swing.JMenuItem menuAlumno;
    private javax.swing.JMenuItem menuInscripcion;
    private javax.swing.JMenuItem menuMateria;
    private javax.swing.JMenuItem menuNotas;
    private javax.swing.JMenuItem menuSalirPrograma;
    // End of variables declaration//GEN-END:variables
}
